### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by asapverneri** [dran1x/CS2-AutoUpdater#6]
Hi, Im on latest css v141 & meta and i got this error.

`17:48:26 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'CS2AutoUpdater.CS2AutoUpdater' threw an exception.
 ---> CounterStrikeSharp.API.Core.NativeException: Global Variables not initialized yet.
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.GetMaxClients() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 320
   at CounterStrikeSharp.API.Server.get_MaxPlayers() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Server.cs:line 78
   at CS2AutoUpdater.CS2AutoUpdater..cctor()
   --- End of inner exception stack trace ---
   at CS2AutoUpdater.CS2AutoUpdater.OnMapEnd()
   at InvokeStub_OnMapEnd.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass45_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 365
   at InvokeStub_Action`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 46`

**Comment by BrutalCSEjziponken** [comment]
I have the same thing.

**Comment by Stimayk** [comment]
I fixed it.
https://github.com/dran1x/CS2-AutoUpdater/pull/7

**Comment by BrutalCSEjziponken** [comment]
> I fixed it. #7

[2024-01-07 03:20:05] [AutoUpdater] 'sv_hibernate_when_empty' is enabled. This plugin might not work as expected.

Console: sv_hibernate_when_empty = false

**Comment by Stimayk** [comment]
> > I fixed it. #7
> 
> [2024-01-07 03:20:05] [AutoUpdater] 'sv_hibernate_when_empty' is enabled. This plugin might not work as expected.
> 
> Console: sv_hibernate_when_empty = false

This message was there before, my changes did not affect it in any way.
And just for information, the main thing is that this value (sv_hibernate_when_empty) should be "true" in server.cfg or other cfg file that will be applied, then everything works fine.
